# Generated by Django 3.0.6 on 2020-07-20 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Starting', models.CharField(max_length=255)),
                ('Ending', models.CharField(max_length=255)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crouselimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crouselimg1', models.ImageField(upload_to='')),
                ('crouselimg2', models.ImageField(upload_to='')),
                ('crouselimg3', models.ImageField(upload_to='')),
                ('crouselabel1', models.CharField(max_length=222)),
                ('crouselabel2', models.CharField(max_length=222)),
                ('crouselabel3', models.CharField(max_length=222)),
                ('crouseltext1', models.CharField(max_length=222)),
                ('crouseltext2', models.CharField(max_length=222)),
                ('crouseltext3', models.CharField(max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('textreview', models.TextField()),
                ('userdate', models.DateTimeField(default=datetime.datetime(2020, 7, 20, 19, 58, 48, 478653))),
            ],
        ),
    ]
