# Generated by Django 3.0.6 on 2020-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='crouselimg',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
