# Generated by Django 3.0.6 on 2020-07-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_destination_crouselimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='crouselimg',
            new_name='crouselimg1',
        ),
        migrations.AddField(
            model_name='destination',
            name='crouselimg2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='crouselimg3',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
