# Generated by Django 3.0.6 on 2020-07-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_auto_20200706_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crouselimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crouselimg1', models.ImageField(upload_to='')),
                ('crouselimg2', models.ImageField(upload_to='')),
                ('crouselimg3', models.ImageField(upload_to='')),
                ('crouselabel1', models.CharField(max_length=222)),
                ('crouselabel2', models.CharField(max_length=222)),
                ('crouselabel3', models.CharField(max_length=222)),
                ('crouseltext1', models.CharField(max_length=222)),
                ('crouseltext2', models.CharField(max_length=222)),
                ('crouseltext3', models.CharField(max_length=222)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='crouselimg1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='crouselimg2',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='crouselimg3',
        ),
    ]
