# Generated by Django 3.0.6 on 2020-07-20 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20200720_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_no',
            field=models.CharField(max_length=222),
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 21, 25, 21, 596881)),
        ),
    ]
