# Generated by Django 3.0.6 on 2020-07-17 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_auto_20200717_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='busid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 12, 7, 32, 378990)),
        ),
    ]
