# Generated by Django 3.0.6 on 2020-07-17 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_auto_20200717_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.AlterField(
            model_name='bus',
            name='busid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 12, 8, 35, 789616)),
        ),
    ]
