# Generated by Django 3.0.6 on 2020-07-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_auto_20200717_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='busid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 16, 35, 1, 149544)),
        ),
    ]
