# Generated by Django 3.0.6 on 2020-07-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0012_auto_20200717_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='busid',
        ),
        migrations.AddField(
            model_name='bus',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 16, 35, 21, 234692)),
        ),
    ]
