# Generated by Django 3.0.6 on 2020-07-17 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0013_auto_20200717_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 16, 36, 25, 249354)),
        ),
    ]
