# Generated by Django 3.0.6 on 2020-07-17 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0015_auto_20200717_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 16, 47, 17, 646660)),
        ),
    ]
