# Generated by Django 3.0.6 on 2020-07-17 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0018_auto_20200717_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 16, 54, 11, 645339)),
        ),
    ]
