# Generated by Django 3.0.6 on 2020-07-17 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0020_auto_20200717_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='Ending',
            new_name='ending',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='Starting',
            new_name='starting',
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 17, 0, 25, 956749)),
        ),
    ]
