# Generated by Django 3.0.6 on 2020-07-17 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0021_auto_20200717_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='ending',
            new_name='Ending',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='starting',
            new_name='Starting',
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 17, 2, 26, 736657)),
        ),
    ]
