# Generated by Django 3.0.6 on 2020-07-17 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0022_auto_20200717_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 17, 11, 52, 526369)),
        ),
    ]
