# Generated by Django 3.0.6 on 2020-07-18 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0025_auto_20200717_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_id',
        ),
        migrations.AddField(
            model_name='bus',
            name='Ticketno',
            field=models.IntegerField(default=924),
        ),
        migrations.AddField(
            model_name='bus',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='userdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 11, 12, 41, 416031)),
        ),
    ]
